ARDUINO_LIBS      := Adafruit_GFX Adafruit_SSD1306 SPI Wire
ARDUINO_PORT      := /dev/ttyUSB1
USER_LIB_PATH     := $(realpath ./lib)
BOARD_TAG         := uno

CXXFLAGS += -std=gnu++11
CFLAGS   += -std=gnu11

include Arduino.mk
